E2E/MDW Governance - De-Identify dataset before move to Bronze w. Presidio
Azure-Samples/modern-data-warehouse-dataops pull request #319
Opened 2021-05-05 18:41 UTC by balteravishay

# Type of PR

- Documentation changes
- Code changes
- CI-CD changes

## Purpose
This PR adds a stage to the modern-data-warehouse governance sample which anonymizes the description column of the dataset using Presidio. This stage is implemented using Azure Databricks, before the dataset is saved to Bronze container.

## Does this introduce a breaking change? If yes, details on what can break

## Author pre-publish checklist

- [ ] Added test to prove my fix is effective or new feature works
- [ ] No PII in logs
- [v] Made corresponding changes to the documentation

2021-05-07 06:49 UTC, devlace requested changes
Thanks @balteravishay! I've quickly reviewed the docs and left some comments. I'm still testing out the sample and will leave comments after then. Hoping to finish by early next week. Also, some of the PR checks (linting/link checks) are failing.

2021-05-07 06:49 UTC, devlace commented on e2e_samples/mdw_governance/README.md
> +The sample focuses on data governance, using Purview, to track data assets and lineage to allow data managers to understand the quality and source of the data, as well as to understand if there is PI
This seems to completely replace the above paragraph. Can you append the last sentence "It also uses presidio..." to the end of the paragraph instead? Also typo: reduce*

2021-05-07 06:49 UTC, devlace commented on e2e_samples/mdw_governance/README.md
> +This solution sets up an Azure Data Lake storage account, with two containers: Datalake and Dropzone. The folder structure in datalake is structured to enable data tiering (Bronze, Silver, Gold), hol
Could you also add a link to the existing single tech sample which demonstrates locking down a Databricks environment: https://github.com/Azure-Samples/modern-data-warehouse-dataops/tree/master/single_tech_samples/databricks/sample2_enterprise_azure_databricks_environment

2021-05-19 07:58 UTC, balteravishay commented
@devlace PR comments are resolved.

2021-05-26 22:53 UTC, devlace approved these changes

2021-05-26 22:54 UTC, merged