feat: observabiltiy-as-code
Azure-Samples/modern-data-warehouse-dataops pull request #479
Opened 2022-02-05 03:16 UTC by sudivate

# Type of PR

- Code changes
- Documentation changes

## Purpose
- Improvements Observability by adding below resources for Observability-as-code in Bicep modules
   -  Azure Dashboard to monitor key metrics from Azure Data Factory and Azure SQL Server
   - Azure Log Analytics Workspace to collect monitoring Data
   - Enabled diagnostic settings for Azure Data Factory
   - Azure Monitor alert for Azure Data Factory Pipelines
- Demonstrated Data Quality monitoring using OSS Great Expectations in Standardize and Transformation steps of Data pipeline 
-  Sample Data Quality Azure Monitor workbook
-  Updated Docs relevant to all above changes

## Does this introduce a breaking change? If yes, details on what can break

## Author pre-publish checklist
- [ ] Added test to prove my fix is effective or new feature works
- [x] No PII in logs
- [x] Made corresponding changes to the documentation

2022-03-23 23:05 UTC, devlace commented
Updated the .NET version to 4.7 to resolve build error

2022-03-28 09:18 UTC, devlace commented
@sudivate Running into an error in the Databricks notebook. 
![image](https://user-images.githubusercontent.com/5771063/160367131-c084ca6f-8401-4c47-8c67-620792183e3f.png)
Looks like its related to a recent breaking change on jinja's side: https://github.com/pallets/jinja/issues/1626

2022-03-28 23:10 UTC, devlace requested changes

2022-03-29 11:02 UTC, devlace commented on e2e_samples/parking_sensors/databricks/notebooks/02_standardize.py
> +context.create_expectation_suite(expectation_suite_name=expectation_suite_name, overwrite_existing=True)
As discussed, we'll keep this simple and keep the creation of the expectation suite in the notebook.

2022-03-29 11:02 UTC, devlace approved these changes

2022-03-29 18:26 UTC, merged

2022-03-29 18:28 UTC, sudivate commented
Thank you @devlace.