Azure Data Share sample
Azure-Samples/modern-data-warehouse-dataops pull request #585
Opened 2023-01-05 18:39 UTC by QuickNS

# Type of PR

- Documentation changes
- Code changes

## Purpose

- Adding a sample about Azure Data Share that fully automates the share invitation process by using a service principal as the recipient of the invite.
- Includes Python scripts to originate the invite and to accept the invitation
- Sample implements an end-to-end scenario where data will be shared between two Data Share accounts and mapped to ADLS Gen2 Storage accounts.
- Includes infrastructure scripts to setup a demo environment
- Includes an Azure Function for a fully automated process that can run unattended

## Does this introduce a breaking change? If yes, details on what can break
No

## Author pre-publish checklist

- [x] Added test to prove my fix is effective or new feature works
- [x] No PII in logs
- [x] Made corresponding changes to the documentation

## Validation steps

- Sample includes step by step instructions on how to run the scenario.

## Issues Closed or Referenced

- Closes #573

2023-01-13 12:14 UTC, ydaponte requested changes
Leaving first comments for you to check. I have again an issue with the Azure Function, but will try to work it out to finish the testing and add final comments if needed.

2023-01-13 16:29 UTC, QuickNS commented on single_tech_samples/datashare/Readme.md
> +- Remember that permissions can be granted by using the `bash_setup_sp_permissions.sh` or `ps_setup_sp_permissions.sh` script in the `infra` folder.
Added a section at the end with cleanup instructions

2023-01-13 16:30 UTC, QuickNS commented on single_tech_samples/datashare/Readme.md
> +
Added a "Using the sample" section

2023-01-13 16:30 UTC, QuickNS commented on single_tech_samples/datashare/Readme.md
> +A dev container is included to allow for an easier setup of your local dev environment. It includes all the required dependencies to execute the code and is the recommended way of testing this sample
Nice catch. Fixed!

2023-01-13 16:31 UTC, QuickNS commented on single_tech_samples/datashare/Readme.md
> +- [Data Share Automation](#data-share-automation)
Moved the table of contents to a new "Contents" section that only includes the remaining topics in the doc

2023-01-13 16:34 UTC, QuickNS commented on single_tech_samples/datashare/Readme.md
> +If you used the *infra* scripts in this repo to create the resources, the role assignements have been setup automatically.
One of the challenges of writing this doc is trying to ensure instructions work in both cases (using the infra scripts or trying with pre-existing assets, or manually created assets). After a bit of back and forth, I decided this iterative approach where settings and roles are mentioned when they are needed in the tutorial steps works better than trying to list them upfront. So I'll just move the line and rephrase it a bit.

2023-01-13 16:40 UTC, QuickNS commented on single_tech_samples/datashare/Readme.md
> +The objectId will be used in the `source.py` script as the target of the invitation. You will need to add the object_id
yes, this phrase was clearly left incomplete, so I just rephrased this whole section.

2023-01-13 17:09 UTC, QuickNS commented on single_tech_samples/datashare/Readme.md
> +./infra/bash_setup_sp_permissions.sh <suffix> <objectId>
it works both ways apparently.

2023-01-13 17:14 UTC, QuickNS commented on single_tech_samples/datashare/Readme.md
> +After the invitation is accepted, the script can't be run again. If you need to re-run it, please create a new invitation using the `dest.py` python script.
yes, fixed

2023-01-13 17:15 UTC, QuickNS commented on single_tech_samples/datashare/Readme.md
> +
Following your suggestion, I restructured the document a bit. Please review.

2023-01-26 12:09 UTC, ydaponte approved these changes
Readability improved a lot with the changes. Thanks for doing them. I'm approving the PR now.

2023-01-26 12:17 UTC, merged