ydaponte/580 582 smart ingest with config file
Azure-Samples/modern-data-warehouse-dataops pull request #592
Opened 2023-01-18 19:37 UTC by ydaponte

# Type of PR

- Code changes

## Purpose
- Add a configuration file that should drive the smart ingestion in the Data Lake.
- Modify the existing pipeline to ingest or update data lake based on configuration file.

## Does this introduce a breaking change? No.

## Author pre-publish checklist
- [X] No PII in logs
- [ ] Made corresponding changes to the documentation (not yet)

## Validation steps
- Deploy the sample as per the instructions
- Run the Pl_NYCTaxi_0_Main pipeline
- Check on the Monitor the pipeline run should succeed

## Issues Closed or Referenced
- Closes #580 
- Closes #582 

- References #578

2023-01-18 21:05 UTC, sreedhar-guda approved these changes
Config changes look good. Might be good if Linked services are reviewed by someone with more experience. Approving to move forward with Hackathon..

2023-01-19 09:30 UTC, elenaterenzi commented
Just a note that yo u should change the branch you are targeting from main to the feature branch @ydaponte

2023-01-19 11:13 UTC, elenaterenzi requested changes
Requesting my comments to be reviewed other than that LGTM

2023-01-19 11:14 UTC, elenaterenzi approved these changes

2023-01-19 11:46 UTC, merged