Add data contextualization using sql graph to single_tech_samples
Azure-Samples/modern-data-warehouse-dataops pull request #619
Opened 2023-02-14 08:52 UTC by cchenshu

# Type of PR

- Documentation changes
- Code changes
- Test changes
- CI-CD changes
- GitHub Template changes

## Purpose

- ...

## Does this introduce a breaking change? If yes, details on what can break

## Author pre-publish checklist

- [ ] Added test to prove my fix is effective or new feature works
- [ ] No PII in logs
- [ ] Made corresponding changes to the documentation

## Validation steps

- ...

## Issues Closed or Referenced

- Closes #issue_number

- References #issue_number

2023-03-08 04:12 UTC, promisinganuj commented
@cchenshu Can we have `DataContextualizationSolution.md` merged to `README.md`? Also, I would suggest to make `DataContextualizationSolution.md` a lot lighter as we have already added most the information into playbook. For this sample, we can just keep the details which are really relevant.

2023-03-08 04:18 UTC, promisinganuj requested changes
Some minor changes.

2023-03-08 04:18 UTC, promisinganuj commented on single_tech_samples/databricks/sample5_data_contextualization_sql_graph/README.md
> +    ![Create-SQL-graph](./images/Create-SQL-graph.png =500x)
Seems like the image is not rendering correctly because of sizing. Please have a look.

2023-03-08 04:18 UTC, promisinganuj commented on single_tech_samples/databricks/sample5_data_contextualization_sql_graph/README.md
> +    ![import](./images/import_databricks.png =700x)
Image rendering issue.

2023-03-08 04:18 UTC, promisinganuj commented on single_tech_samples/databricks/sample5_data_contextualization_sql_graph/README.md
> +            ![import](./images/demo-databricks-notebook-01.png =500x)
Image rendering issue.

2023-03-08 04:18 UTC, promisinganuj commented on single_tech_samples/databricks/sample5_data_contextualization_sql_graph/src/notebooks/demo-setup.py
> +dbutils.fs.rm("/mnt/honeywell/raw/tbl_alarm_master", True)
Please remove any PII information from the repo.

2023-03-08 04:18 UTC, promisinganuj commented on single_tech_samples/databricks/sample5_data_contextualization_sql_graph/README.md
> +# Introduction
Can we add a dev container for running this sample?

2023-03-08 04:19 UTC, promisinganuj commented on single_tech_samples/databricks/sample5_data_contextualization_sql_graph/src/sql/create-graph.sql
> +DROP TABLE IF EXISTS Alarm;
Can we create a specific "database" for these tables?

2023-05-29 04:12 UTC, promisinganuj commented
@gary918 , @cchenshu , now that we have published the [blog](https://learn.microsoft.com/en-us/azure/architecture/example-scenario/data/data-contextualization-based-on-azure-sql-graph), we can go ahead with this sample. 
I will review it this week.

2024-10-29 20:19 UTC, devlace commented
To be retired

2024-11-06 06:12 UTC, promisinganuj commented
Hi @devlace , instead of deleting the whole changes, I have moved this sample to archive folder. Please have a look, we would need to merge it by bypassing branch protections.

2024-11-12 03:48 UTC, devlace approved these changes

2024-11-12 03:55 UTC, merged