Update devcontainer with java and non-root user
Azure-Samples/modern-data-warehouse-dataops pull request #776
Opened 2024-10-31 20:32 UTC by bsherwin

# Type of PR
- Code changes

## Purpose
Fix issue #644 - Devcontainer failing with unsupported JDK
Fix issue #646 - Devcontainer changes file ownership in linux/wsl
Updates devcontainer to bring Critical and High CVE vulnerabilities reported to zero

## Does this introduce a breaking change? If yes, details on what can break
No

## Validation steps
- Clone branch
- Open VSCode folder in DevContainer
- In devcontainer terminal prompt, verify java version: `java -version`
- In devcontainer terminal prompt, run the command `touch test.file`
- In local WSL prompt, navigate to `/mnt/.../e2e_samples/parking_sensors` (replace "..." with location where you cloned the code)
- Validate you can edit the test.file without requiring root permission.

## Issues Closed or Referenced
- Closes #644, #646

2024-10-31 20:34 UTC, bsherwin commented
@StromFLIX and @cpeeyush: Given you submitted PRs over a year ago, I wanted to include you in the review request. We did a few more updates given CVE vulnerabilities, but your changes/suggestions should be represented in the PR updates. We welcome any feedback from you.

2024-11-04 09:44 UTC, ydaponte requested changes
The container started successfully. I left some comments to address and let's have a quick call on the postcreate.sh execution when you read this! Thanks for fixing it!

2024-11-04 09:44 UTC, ydaponte commented on e2e_samples/parking_sensors_synapse/.devcontainer/Dockerfile
Let's not include this changes in this PR as this is related with the Synapse sample and it is being retired at the moment.

2024-11-04 09:44 UTC, ydaponte commented on e2e_samples/parking_sensors_synapse/.devcontainer/devcontainer.json
Same as previous. Let's not mix the Databricks work with the Synapse as it is already being retired.

2024-11-04 09:44 UTC, ydaponte commented on e2e_samples/parking_sensors_synapse/.devcontainer/devcontainer.json
>  	"postCreateCommand": "./.devcontainer/post_create.sh"
While testing and I get to the post_create.sh command I get the following error: 
postCreateCommandfailed with exit code 127. Skipping any further user-provided commands. 
Did you also have this problem? Maybe is just a problem on my side, but I would like to confirm with you.

2024-11-04 15:24 UTC, ydaponte approved these changes
LGTM! Thanks for addressing the comments!

2024-11-04 18:08 UTC, merged