Adding sample utility script
Azure-Samples/modern-data-warehouse-dataops pull request #793
Opened 2024-11-10 23:07 UTC by promisinganuj

# Type of PR

- Documentation changes
- Code changes

## Purpose

- Adding a sample "utility" script as an example.

## Does this introduce a breaking change? If yes, details on what can break

No, standalone script

## Author pre-publish checklist

- [x] Added test to prove my fix is effective or new feature works
- [x] No PII in logs
- [x] Made corresponding changes to the documentation

## Validation steps

- Execute the script to upload a file from local/git to Fabric Lakehouse.

## Issues Closed or Referenced

- Closes #769

2024-11-12 03:49 UTC, devlace approved these changes

2024-11-13 01:52 UTC, naga-nandyala requested changes
...

2024-11-13 04:04 UTC, naga-nandyala requested changes

2024-11-13 04:24 UTC, promisinganuj commented on utilities/fabric/README.md
> +  AZURE_CLIENT_ID="<Azure SP client id>"
I have left the AZURE_* variable as it because it's required for "DefaultAzureCredential". Rest have been made consistent.

2024-11-13 04:29 UTC, naga-nandyala approved these changes

2024-11-13 04:57 UTC, merged