update for cluster config and template
Azure-Samples/modern-data-warehouse-dataops pull request #941
Opened 2024-12-10 15:08 UTC by thesqlpro

# Type of PR

- Documentation changes
- Code changes
- Test changes
- CI-CD changes
- GitHub Template changes

## Purpose
Update cluster configuration and template file. Newer spark version and change to auto termination (reduced to 10 minutes).

## Does this introduce a breaking change? If yes, details on what can break

## Author pre-publish checklist

- [NA ] Added test to prove my fix is effective or new feature works
- [x ] No PII in logs
- [ NA] Made corresponding changes to the documentation

## Validation steps

- ...

## Issues Closed or Referenced

- Closes #issue_number

- References #issue_number

2024-12-11 10:38 UTC, ydaponte requested changes
This change alone will not work - you need to deploy the sample e2e and test: 
1) The deployment itself (running deploy.sh) - because when the deployment tries to install the libraries in the cluster they will fail on this version because DBFS will no longer be available on the cluster. 
2) The ADF pipelines will fail because the libraries will not be properly installed. My suggestion is deploy the solution with the Spark 15.4  version and start fixing in the interface the problems  - when you know what to change then integrate the automation and run the deployment again e2e and make sure is working before submitting the PR.

Also, please update the metadata in the PR properly and describe the Type of PR - you left all the bullets, include the validation steps and which issues will be closed or reference when the PR closes. The body of the PR looks just like the template. Thanks!

2024-12-13 19:19 UTC, thesqlpro commented
Documenting the issues @ydaponte listed
configure_Databricks.sh
line 88-102
echo "Uploading libs TO dbfs..."
databricks fs cp --recursive --overwrite "./databricks/libs/ddo_transform-localdev-py2.py3-none-any.whl" "dbfs:/ddo_transform-localdev-py2.py3-none-any.whl"

# Create JSON file for library installation
json_file="./databricks/config/libs.config.json"
cat <<EOF > $json_file
{
  "cluster_id": "$cluster_id",
  "libraries": [
    {
      "whl": "dbfs:/ddo_transform-localdev-py2.py3-none-any.whl"
    }
  ]
}
EOF


All of the notebooks reference a dbfs location

2024-12-16 16:49 UTC, ydaponte commented
@thesqlpro - yes, precisely, that was a temporary solution until we have the Unity Catalog + new Spark version in place. I've mention that on the very first sprint  why I've mentioned that the dbfs file system will not be available anymore with the 15.4 version.

2024-12-23 19:59 UTC, thesqlpro commented
This is not part of a feature #765 
Has pre-requisites that need to be completed first. However the task itself is complete and ready to push after the other tasks before it are completed.

2025-01-16 08:23 UTC, closed without merging

2025-01-16 08:23 UTC, ydaponte commented
Abandoning this PR as it needs further research and integration with other moving parts.