Upgrading bicep templates #886
Azure-Samples/modern-data-warehouse-dataops pull request #954
Opened 2024-12-13 14:12 UTC by raafatzarka

# Type of PR
- Code changes

## Purpose
Review all bicep modules from the sample and upgrade to the newest version

## Does this introduce a breaking change? If yes, details on what can break

## Author pre-publish checklist

- [ ] Added test to prove my fix is effective or new feature works
- [ ] No PII in logs
- [ ] Made corresponding changes to the documentation

## Validation steps

- tested the deployment using Dev Container
- All resources have been deployed successfully

## Issues Closed or Referenced

- Closes #886 

- References #995

2024-12-13 15:02 UTC, thesqlpro approved these changes
looks good

2024-12-14 01:07 UTC, ydaponte commented
@raafatzarka - it seems you still have conflicts with the base branch.

2024-12-14 01:45 UTC, ydaponte requested changes
Minor question on an added file and conflicts must be resolved.

2024-12-14 01:45 UTC, ydaponte commented on modern-data-warehouse-dataops
What is this file?

2024-12-18 18:06 UTC, ydaponte approved these changes
Approving! Thanks!

2024-12-18 18:08 UTC, merged