[Unity Catalog] - Update Readme for Unity Catalog (#978)
Azure-Samples/modern-data-warehouse-dataops pull request #996
Opened 2024-12-27 17:22 UTC by thesqlpro

# Type of PR
Update to Readme to add Unity Catalog instructions
- Documentation changes

## Purpose
Unity Catalog is a new addition to this repo. By default it is added to all new Databricks workspaces.  This documentation addition allows users of the repo to create a metastore and catalog for this sample.

## Author pre-publish checklist
- [ ] No PII in logs
- [ ] Made corresponding changes to the documentation

## Validation steps

## Issues Closed or Referenced
#978 
Following tasks also rely on it
#982 
#984 
#983 
#765

2025-01-09 10:23 UTC, ydaponte requested changes
Let's have a call on the PRs when you start your day. I would like to have an unique PR as it would be much easier to test and it is a better way to keep related changes together.

2025-01-09 15:11 UTC, thesqlpro commented on e2e_samples/parking_sensors/README.md
> +   - *Permissions needed*: If a regional metastore does not exist then an account admin must create one. [Metastore Creation](https://learn.microsoft.com/en-us/azure/databricks/data-governance/unity-
Made changes

2025-01-13 14:42 UTC, bsherwin requested changes
If there are dependent PRs, please roll them together so the changes go at the same time.

2025-01-13 14:48 UTC, ydaponte commented
@bsherwin - I asked @thesqlpro to consolidate the PRs otherwise it is more challenging to test, but he is OOF until tomorrow. Please give him a day to consolidate.

2025-01-21 07:01 UTC, ydaponte commented
Abandoning the PR as some pre-requisites will be automated.

2025-01-21 07:01 UTC, closed without merging